### ISSUE TITLE
Buildpack should be compatible with both scalingo-14 and scalingo-18

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cairo-buildpack#1]

**Comment by cyrille-sg** [comment]
From last cairo to Ubuntu 18:
- PIXMAN 0.34.0-1
  - 0.34.0-2 (already installed - libpixman-1-0)
- FREETYPE 2.6.3-1
  - 2.8.1 (already installed - libfreetype6)
- GIFLIB 5.1.4-1
  - 5.1.4 (libgif7)  
- PANGO 1.40.1-1
  - 1.40.14 (already installed - libpango-1.0-0)
- CAIRO 1.14.6-1
  - 1.15.10 (already installed - libcairo2)
- FONTCONFIG 2.11.95-1
  - 2.12.6 (already installed - libfontconfig1) 
- HARFBUZZ 1.2.7-1
  - 1.7.2 (already installed - libharfbuzz0b)
